version: '3'

services:
  web:
    restart: always
    build: .
    image: addtel
    environment:
      FLASK_ENV: development
    volumes:
      - "./flaskapp:/home/project/flask_app"
    command: /usr/local/bin/uwsgi --http :8080 --wsgi-file wsgi.py --master --processes 4 --threads 2
    ports:
      - "8080:8080"
