version: '3'

services:

  web:
    restart: always
    build: ./images/flask-docker-gunicorn-base
    environment:
      FLASK_ENV: development
#      FLASK_DEBUG: 1
      GUNICORN_RELOAD: "true"
      GUNICORN_LOGLEVEL: "warning"    # debug
    volumes:
      - "./flaskapp/:/home/project/flask_app"

  nginx:
    restart: always
    build: ./images/nginx
    ports:
      - "8080:80"
    depends_on:
      - web