version: '3'

services:

  web:
    restart: always
    build: ./images/flask-docker-gunicorn-base
    environment:
      # replaces Flask Debug
      FLASK_ENV: debug
      GUNICORN_RELOAD: "true"
      GUNICORN_LOGLEVEL: "warning"
      DB_BACKEND: 'sqlite'
      DB_NAME: "addtel"
      DB_USER: "addtel"
      DB_PASSWORD: "changeforprod"
      LOCAL_USER_ID: 1000
    volumes:
      - "./src:/src"
      - "static:/var/www/static"
#      - "media:/code/www/media"

  nginx:
    container_name: nginx
    restart: always
    build: ./images/nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - "static:/var/www/static"
      - "media:/var/www/media"
    environment:
      LOCAL_USER_ID: 1000


#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    hostname: postgres
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: telscraper
#      POSTGRES_PASSWORD: vood005643
#      POSTGRES_DB: TEST_SM
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pdadmin
#    depends_on:
#      - postgres
#    ports:
#      - "4444:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: admin
#    volumes:
#      - pgadmin_config:/var/lib/pgadmin
##      - "/private/var/lib/pgadmin:/var/lib/pgadmin"
#

volumes:
  static:
  media:
  #  pgdata:
  #  pgadmin_config:
